### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by zc-maker** [Kazuhito00/YOLOP-ONNX-Video-Inference-Sample#1]
感谢你做的工作，对我很有帮助，但是有没有考虑过，如何完善车道线的显示，感觉目前的车道线是有一些问题的

**Comment by Kazuhito00** [comment]
我不做模型训练。
如果您对模型准确性有任何疑问，请联系官方存储库。

https://github.com/hustvl/YOLOP

**Comment by Kazuhito00** [comment]
它将关闭，因为时间已经过去。
如果您有任何问题，请重新提交表格。
